// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUKDWt0dKHL9LiijHmHh_NOsVP9ZOlbpw',
    appId: '1:1030071161857:web:3e1f9cff78ea5eeb3d9c00',
    messagingSenderId: '1030071161857',
    projectId: 'flutter-lab-2-c3651',
    authDomain: 'flutter-lab-2-c3651.firebaseapp.com',
    storageBucket: 'flutter-lab-2-c3651.firebasestorage.app',
    measurementId: 'G-PXPPZ8B4YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWgDl7B7EiaADbIuenFbh83RbMF9e-pU',
    appId: '1:1030071161857:android:1c126aa1d38dcf333d9c00',
    messagingSenderId: '1030071161857',
    projectId: 'flutter-lab-2-c3651',
    storageBucket: 'flutter-lab-2-c3651.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAQhAZ4uW_hvX5D2nBTerCsHzy6kWUog',
    appId: '1:1030071161857:ios:f3afff4952716d383d9c00',
    messagingSenderId: '1030071161857',
    projectId: 'flutter-lab-2-c3651',
    storageBucket: 'flutter-lab-2-c3651.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqAQhAZ4uW_hvX5D2nBTerCsHzy6kWUog',
    appId: '1:1030071161857:ios:f3afff4952716d383d9c00',
    messagingSenderId: '1030071161857',
    projectId: 'flutter-lab-2-c3651',
    storageBucket: 'flutter-lab-2-c3651.firebasestorage.app',
    iosBundleId: 'com.example.lab1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUKDWt0dKHL9LiijHmHh_NOsVP9ZOlbpw',
    appId: '1:1030071161857:web:63640020a62dc2243d9c00',
    messagingSenderId: '1030071161857',
    projectId: 'flutter-lab-2-c3651',
    authDomain: 'flutter-lab-2-c3651.firebaseapp.com',
    storageBucket: 'flutter-lab-2-c3651.firebasestorage.app',
    measurementId: 'G-EB3994KFWX',
  );

}